// src/lib/settingsSearch.ts

export type SettingSectionKey =
  | 'subscription'
  | 'appearance'
  | 'reminders'
  | 'learning'
  | 'budget'
  | 'data'
  | 'about'
  | 'danger';

export type SettingItemKey =
  | 'subscription'
  | 'theme'
  | 'language'
  | 'accent'
  | 'motion'
  | 'sounds'
  | 'glossary'
  | 'widgetMascot'
  | 'reminder_spending'
  | 'reminder_owed'
  | 'reminder_commitments'
  | 'learning'
  | 'budget'
  | 'data_commitments'
  | 'data_tax'
  | 'data_categories'
  | 'data_currencies'
  | 'data_import'
  | 'data_export'
  | 'data_backup'
  | 'data_diagnostics'
  | 'about_version'
  | 'about_privacy'
  | 'about_terms'
  | 'about_manage'
  | 'about_tutorial'
  | 'about_connect'
  | 'about_bug'
  | 'danger_reset_all'
  | 'danger_reset_setup';

export interface SettingDefinition {
  key: SettingItemKey;
  section: SettingSectionKey;
  sectionTitleEn: string;
  sectionTitleZh: string;
  titleEn: string;
  titleZh: string;
  keywords: string[];
}

export const SETTING_DEFINITIONS: SettingDefinition[] = [
  {
    key: 'subscription',
    section: 'subscription',
    sectionTitleEn: 'Pip Pro',
    sectionTitleZh: 'Pip Pro',
    titleEn: 'Pip Pro',
    titleZh: 'Pip Pro',
    keywords: [
      'pro',
      'subscription',
      'upgrade',
      'pip pro',
      'restore',
      'manage',
      'cancel',
      'membership',
      'vip',
      'premium',
      '会员',
      '订阅',
      '恢复购买',
      '取消订阅',
      '高级版',
    ],
  },
  {
    key: 'theme',
    section: 'appearance',
    sectionTitleEn: 'Appearance',
    sectionTitleZh: '外观与偏好',
    titleEn: 'Theme',
    titleZh: '主题模式',
    keywords: [
      'theme',
      'dark',
      'light',
      'system',
      'mode',
      'color mode',
      'dark mode',
      'light mode',
      'night',
      'appearance',
      '主题',
      '浅色',
      '深色',
      '系统',
      '夜间模式',
      '黑夜模式',
      '日间模式',
    ],
  },
  {
    key: 'language',
    section: 'appearance',
    sectionTitleEn: 'Appearance',
    sectionTitleZh: '外观与偏好',
    titleEn: 'Language',
    titleZh: '语言设置',
    keywords: [
      'language',
      'english',
      'chinese',
      'simplified chinese',
      'mandarin',
      'locale',
      'translation',
      'i18n',
      'en',
      'zh',
      '语言',
      '英文',
      '中文',
      '简体中文',
      '翻译',
    ],
  },
  {
    key: 'accent',
    section: 'appearance',
    sectionTitleEn: 'Appearance',
    sectionTitleZh: '外观与偏好',
    titleEn: 'Accent color & App icon',
    titleZh: '主题强调色与应用图标',
    keywords: [
      'accent',
      'color',
      'colour',
      'accent color',
      'preset',
      'app icon',
      'icon',
      'squircle',
      'ink',
      'monochrome',
      'mono',
      'black and white',
      'black white',
      'grayscale',
      'greyscale',
      'style',
      'amber',
      'emerald',
      'forest',
      'green',
      'berry',
      'purple',
      'ocean',
      'blue',
      'coral',
      'peach',
      '强调色',
      '颜色',
      '图标',
      '应用图标',
      '色彩',
      '个性化',
      '单色',
      '黑白',
      '墨色',
      '风格',
    ],
  },
  {
    key: 'motion',
    section: 'appearance',
    sectionTitleEn: 'Appearance',
    sectionTitleZh: '外观与偏好',
    titleEn: 'Motion and haptics',
    titleZh: '动画与触感反馈',
    keywords: [
      'motion',
      'haptics',
      'animation',
      'reduced motion',
      'vibration',
      'transition',
      'full',
      'reduced',
      'off',
      'speed',
      'smoothness',
      'feedback',
      '动画',
      '触感',
      '震动',
      '减弱',
      '动效',
      '反馈',
    ],
  },
  {
    key: 'widgetMascot',
    section: 'appearance',
    sectionTitleEn: 'Appearance',
    sectionTitleZh: '外观与偏好',
    titleEn: 'Widget mascot',
    titleZh: '小组件挂件',
    keywords: [
      'widget',
      'mascot',
      'pip',
      'hat',
      'eyes',
      'mouth',
      'streak badge',
      'home screen',
      'customize',
      'customise',
      '小组件',
      '挂件',
      '桌面',
      '帽子',
      '眼睛',
      '嘴巴',
      '自定义',
    ],
  },
  {
    key: 'sounds',
    section: 'appearance',
    sectionTitleEn: 'Appearance',
    sectionTitleZh: '外观与偏好',
    titleEn: 'Sounds',
    titleZh: '提示音效',
    keywords: [
      'sounds',
      'sound',
      'audio',
      'chime',
      'payoff',
      'effect',
      'tone',
      'ding',
      'save chime',
      'mute',
      'volume',
      '音效',
      '提示音',
      '声音',
      '静音',
      '音量',
    ],
  },
  {
    key: 'glossary',
    section: 'appearance',
    sectionTitleEn: 'Appearance',
    sectionTitleZh: '外观与偏好',
    titleEn: 'Glossary',
    titleZh: '词汇解释',
    keywords: [
      'glossary',
      'info',
      'info button',
      'help',
      'definitions',
      'explain',
      'tooltip',
      '词汇',
      '词汇解释',
      '说明',
      '帮助',
      '名词解释',
    ],
  },
  {
    key: 'reminder_spending',
    section: 'reminders',
    sectionTitleEn: 'Reminders',
    sectionTitleZh: '通知与提醒',
    titleEn: 'Log your spending',
    titleZh: '记账提醒',
    keywords: [
      'reminder',
      'log spending',
      'spending',
      'notification',
      'cadence',
      'daily',
      'weekly',
      'time',
      'hour',
      'auto',
      'schedule',
      'when',
      '9 pm',
      '10 pm',
      '11 pm',
      '提醒',
      '通知',
      '记账',
      '每日',
      '每周',
      '定时',
      '时间',
    ],
  },
  {
    key: 'reminder_owed',
    section: 'reminders',
    sectionTitleEn: 'Reminders',
    sectionTitleZh: '通知与提醒',
    titleEn: 'Chase what you’re owed',
    titleZh: '催款提醒 / 还款提醒',
    keywords: [
      'reminder',
      'chase owed',
      'owed',
      'debt',
      'split',
      'borrow',
      'lent',
      'friends',
      'notification',
      '提醒',
      '催款',
      '借出',
      '分账',
      '未还款',
      '还钱',
      '应收款',
    ],
  },
  {
    key: 'reminder_commitments',
    section: 'reminders',
    sectionTitleEn: 'Reminders',
    sectionTitleZh: '通知与提醒',
    titleEn: 'Recurring bills',
    titleZh: '定期账单提醒',
    keywords: [
      'reminder',
      'recurring bills',
      'recurring',
      'bill',
      'subscription',
      'due',
      'commitment',
      'notification',
      '提醒',
      '订阅',
      '固定账单',
      '定期扣款',
      '到期',
    ],
  },
  {
    key: 'learning',
    section: 'learning',
    sectionTitleEn: 'Learning',
    sectionTitleZh: '智能记忆',
    titleEn: 'Learned merchants',
    titleZh: '商家智能记忆',
    keywords: [
      'learning',
      'learned',
      'merchants',
      'merchant',
      'memory',
      'auto-categorization',
      'clear memory',
      'reset learning',
      'smart',
      'ai learning',
      '记忆',
      '商家记忆',
      '智能学习',
      '自动分类',
      '重置记忆',
      '已学习',
    ],
  },
  {
    key: 'budget',
    section: 'budget',
    sectionTitleEn: 'Budget',
    sectionTitleZh: '预算管理',
    titleEn: 'Budget',
    titleZh: '预算设置',
    keywords: [
      'budget',
      'income',
      'expected income',
      'allocations',
      'allocation',
      'category budget',
      'reset budget',
      'plan',
      'monthly budget',
      'safe to spend',
      '预算',
      '收入',
      '分类预算',
      '清空预算',
      '重置预算',
      '额度',
    ],
  },
  {
    key: 'data_commitments',
    section: 'data',
    sectionTitleEn: 'Data',
    sectionTitleZh: '数据与管理',
    titleEn: 'Recurring bills & investments',
    titleZh: '固定账单与投资',
    keywords: [
      'recurring',
      'bills',
      'investments',
      'commitment',
      'subscriptions',
      'stocks',
      'crypto',
      'monthly bills',
      'fixed expenses',
      '固定支出',
      '定期账单',
      '投资',
      '定投',
      '周期',
      '订阅',
    ],
  },
  {
    key: 'data_tax',
    section: 'data',
    sectionTitleEn: 'Data',
    sectionTitleZh: '数据与管理',
    titleEn: 'Tax relief',
    titleZh: '税务减免',
    keywords: [
      'tax',
      'tax relief',
      'deduction',
      'receipts',
      'e-filing',
      'lhdn',
      'claim',
      'rebate',
      'lifestyle',
      'epf',
      'medical',
      '税务',
      '税收减免',
      '退税',
      '报税',
      '收据',
      '扣税',
      '个税',
    ],
  },
  {
    key: 'data_categories',
    section: 'data',
    sectionTitleEn: 'Data',
    sectionTitleZh: '数据与管理',
    titleEn: 'Categories',
    titleZh: '收支分类',
    keywords: [
      'category',
      'categories',
      'icon',
      'color',
      'hue',
      'custom category',
      'expense',
      'income',
      'manage categories',
      '分类',
      '收支分类',
      '类别',
      '图标',
      '自定义分类',
      '编辑分类',
    ],
  },
  {
    key: 'data_currencies',
    section: 'data',
    sectionTitleEn: 'Data',
    sectionTitleZh: '数据与管理',
    titleEn: 'Currencies',
    titleZh: '多币种支持',
    keywords: [
      'currency',
      'currencies',
      'multi-currency',
      'fx',
      'exchange rate',
      'myr',
      'usd',
      'sgd',
      'cny',
      'eur',
      'gbp',
      'jpy',
      'foreign',
      'forex',
      'base currency',
      '货币',
      '汇率',
      '多币种',
      '外币',
      '币种',
      '本位币',
    ],
  },
  {
    key: 'data_import',
    section: 'data',
    sectionTitleEn: 'Data',
    sectionTitleZh: '数据与管理',
    titleEn: 'Advanced import',
    titleZh: '高级导入',
    keywords: [
      'import',
      'advanced import',
      'statement',
      'pdf',
      'csv',
      'excel',
      'xlsx',
      'bank statement',
      'bulk',
      'batch',
      'upload',
      'file',
      '导入',
      '账单导入',
      '对账单',
      '批量导入',
      '银行流水',
      '流水',
    ],
  },
  {
    key: 'data_export',
    section: 'data',
    sectionTitleEn: 'Data',
    sectionTitleZh: '数据与管理',
    titleEn: 'Financial reports & export',
    titleZh: '财务报表与导出',
    keywords: [
      'export',
      'report',
      'financial reports',
      'statement',
      'csv',
      'xlsx',
      'excel',
      'pdf',
      'html',
      'backup',
      'download',
      'data export',
      'summary',
      '导出',
      '报表',
      '财务报表',
      '下载',
      '备份',
      '数据导出',
    ],
  },
  {
    key: 'data_backup',
    section: 'data',
    sectionTitleEn: 'Data',
    sectionTitleZh: '数据与管理',
    titleEn: 'Back Up & Restore',
    titleZh: '备份与恢复',
    keywords: [
      'backup',
      'restore',
      'back up',
      'cloud backup',
      'google drive',
      'icloud',
      'recover',
      'snapshot',
      'sync',
      '备份',
      '恢复',
      '云备份',
      '同步',
      '谷歌云端硬盘',
    ],
  },
  {
    key: 'data_diagnostics',
    section: 'data',
    sectionTitleEn: 'Data',
    sectionTitleZh: '数据与管理',
    titleEn: 'Crash Diagnostics',
    titleZh: '崩溃诊断',
    keywords: [
      'crash',
      'diagnostics',
      'error reporting',
      'bug report',
      'telemetry',
      'analytics',
      'privacy',
      'sentry',
      '崩溃',
      '诊断',
      '错误报告',
      '隐私',
      '遥测',
    ],
  },
  {
    key: 'about_version',
    section: 'about',
    sectionTitleEn: 'About',
    sectionTitleZh: '关于',
    titleEn: 'Version',
    titleZh: '版本',
    keywords: [
      'about',
      'version',
      'build',
      'app version',
      '关于',
      '版本',
      '版本号',
    ],
  },
  {
    key: 'about_privacy',
    section: 'about',
    sectionTitleEn: 'About',
    sectionTitleZh: '关于',
    titleEn: 'Privacy policy',
    titleZh: '隐私政策',
    keywords: [
      'about',
      'privacy',
      'privacy policy',
      'data',
      'gdpr',
      'pdpa',
      '关于',
      '隐私',
      '隐私政策',
    ],
  },
  {
    key: 'about_terms',
    section: 'about',
    sectionTitleEn: 'About',
    sectionTitleZh: '关于',
    titleEn: 'Terms of use',
    titleZh: '使用条款',
    keywords: [
      'about',
      'terms',
      'terms of use',
      'legal',
      'eula',
      '关于',
      '条款',
      '使用条款',
    ],
  },
  {
    key: 'about_manage',
    section: 'about',
    sectionTitleEn: 'About',
    sectionTitleZh: '关于',
    titleEn: 'Manage subscription',
    titleZh: '管理订阅',
    keywords: [
      'about',
      'manage',
      'subscription',
      'cancel',
      'billing',
      'renew',
      '关于',
      '管理订阅',
      '取消订阅',
      '订阅',
    ],
  },
  {
    key: 'about_tutorial',
    section: 'about',
    sectionTitleEn: 'About',
    sectionTitleZh: '关于',
    titleEn: 'Replay Onboarding Tutorial',
    titleZh: '重播新手入门教程',
    keywords: [
      'about',
      'tutorial',
      'onboarding',
      'guide',
      'replay',
      'tour',
      'spotlight',
      'walkthrough',
      'intro',
      'welcome',
      'replay tutorial',
      'help',
      '关于',
      '教程',
      '新手引导',
      '重播',
      '引导',
      '帮助',
      '新手入门',
      '向导',
    ],
  },
  {
    key: 'about_connect',
    section: 'about',
    sectionTitleEn: 'About',
    sectionTitleZh: '关于',
    titleEn: 'Connect with us',
    titleZh: '关注我们',
    keywords: [
      'about',
      'connect',
      'instagram',
      'social',
      'follow',
      'pipsavings',
      'contact',
      '关于',
      '关注我们',
      'instagram',
      '社交',
    ],
  },
  {
    key: 'about_bug',
    section: 'about',
    sectionTitleEn: 'About',
    sectionTitleZh: '关于',
    titleEn: 'Report a bug',
    titleZh: '报告问题',
    keywords: [
      'about',
      'bug',
      'report',
      'problem',
      'issue',
      'crash',
      'broken',
      'sentry',
      '关于',
      '报告问题',
      '反馈',
      '故障',
      '问题',
    ],
  },
  {
    key: 'danger_reset_all',
    section: 'danger',
    sectionTitleEn: 'Danger zone',
    sectionTitleZh: '危险区域',
    titleEn: 'Reset all data',
    titleZh: '清除所有数据',
    keywords: [
      'reset all data',
      'reset',
      'wipe',
      'delete',
      'clear',
      'all data',
      'danger zone',
      'factory reset',
      'erase',
      'remove',
      '重置',
      '清空所有数据',
      '清除所有数据',
      '删除',
      '危险区域',
      '抹掉',
      '清空',
    ],
  },
  {
    key: 'danger_reset_setup',
    section: 'danger',
    sectionTitleEn: 'Danger zone',
    sectionTitleZh: '危险区域',
    titleEn: 'Reset & go to setup',
    titleZh: '重置并进入设置向导',
    keywords: [
      'reset to setup',
      'setup',
      'onboarding',
      'wizard',
      'restart',
      're-setup',
      'reset',
      'danger zone',
      '重新设置',
      '重置并进入设置向导',
      '初始化',
      '向导',
      '重新引导',
    ],
  },
];

export function normalizeQuery(query: string): string {
  return query.trim().toLowerCase();
}

export function matchesSetting(
  def: SettingDefinition,
  query: string,
  extraKeywords?: string[]
): boolean {
  const q = normalizeQuery(query);
  if (!q) return true;

  const terms = q.split(/\s+/).filter(Boolean);

  const searchableText = [
    def.key,
    def.section,
    def.sectionTitleEn,
    def.sectionTitleZh,
    def.titleEn,
    def.titleZh,
    ...def.keywords,
    ...(extraKeywords ?? []),
  ]
    .join(' ')
    .toLowerCase();

  return terms.every((term) => searchableText.includes(term));
}

export function filterSettings(
  query: string,
  dynamicContext?: Partial<Record<SettingItemKey, string[]>>
): {
  matchingKeys: Set<SettingItemKey>;
  isSearching: boolean;
  hasMatches: boolean;
  matchingSections: Set<SettingSectionKey>;
} {
  const q = normalizeQuery(query);
  const isSearching = q.length > 0;

  if (!isSearching) {
    const allKeys = new Set<SettingItemKey>(SETTING_DEFINITIONS.map((d) => d.key));
    const allSections = new Set<SettingSectionKey>(SETTING_DEFINITIONS.map((d) => d.section));
    return {
      matchingKeys: allKeys,
      isSearching: false,
      hasMatches: true,
      matchingSections: allSections,
    };
  }

  const matchingKeys = new Set<SettingItemKey>();
  const matchingSections = new Set<SettingSectionKey>();

  for (const def of SETTING_DEFINITIONS) {
    const extras = dynamicContext?.[def.key];
    if (matchesSetting(def, q, extras)) {
      matchingKeys.add(def.key);
      matchingSections.add(def.section);
    }
  }

  return {
    matchingKeys,
    isSearching: true,
    hasMatches: matchingKeys.size > 0,
    matchingSections,
  };
}
